## options
setopt ignore_eof
setopt prompt_subst
setopt auto_cd
setopt auto_param_keys
setopt auto_param_slash
setopt interactive_comments
setopt no_beep
setopt no_hist_beep
setopt no_list_beep
setopt magic_equal_subst
setopt notify
setopt print_eight_bit
setopt print_exit_value
setopt pushd_ignore_dups
setopt rm_star_wait
setopt transient_rprompt
setopt correct
setopt correct_all
setopt brace_ccl
setopt always_last_prompt
setopt auto_menu
setopt auto_pushd
setopt complete_in_word
setopt globdots
setopt list_types

## history
setopt share_history
setopt pushd_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt extended_history
setopt inc_append_history
